blog/urls.py
from django.urls import path
from . import views

# HTTP Request <-> HTTP Response

app_name = 'blog'

urlpatterns = [
    path('post/<int:post_id>/', views.post, name='post'),
    path('post/', views.blog, name='index'),
    path('example/', views.example, name='example'),
]

first_proj/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path

# HTTP Request <-> HTTP Response


urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from . import views
# HTTP Request <-> HTTP Response

app_name = 'home'

urlpatterns = [
    path('', views.home, name='index'),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from typing import Any
from blog.data import posts

from django.shortcuts import render
from django.http import HttpRequest, Http404

# Create your views here.


def post(request: HttpRequest, post_id: int):
    found_post: dict(str, Any) | None = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
    
    if found_post is None:
        raise Http404('Post não encontrado.')

    context = {
        'post': found_post,
        'title': found_post['title'] + ' - ',
    }

    return render(
        request,
        'blog/post.html',
        context,
    )
def blog(request):
    context = {
        'title': 'Blog',
        'posts': posts,
    }

    return render(
        request,
        'blog/index.html',
        context,
    )

def example(request):
    context = {
        'text': 'Olá Blog'
    }

    return render(
        request,
        'blog/example.html',
        context,
    )

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    context = {
        'text': 'Home',
        'title': 'Home',
    }
    return render(
        request,
        'home/index.html',
        context
    )

blog/templates/blog/example.html
{% extends 'global/base.html' %}

{% block text %}
  {{ text }}
{% endblock text %}

blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block text %}
  {{ text }}
{% endblock text %}

{% block posts %}
    {% for post in posts %}
      {% include 'global/partials/postblock.html' %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends 'global/base.html' %}
{% include 'global/partials/breadcrumbs.html' %}

{% block post %}
  <article class="tile is-vertical">
    <h3 class="title"> 
      <a href="{% url 'blog:post' post.id %}">
        {{ post.title }}
      </a>
    </h3>
    <p> {{ post.body }} </p>
  </article>
{% endblock post %}

home/templates/home/index.html
{% extends 'global/base.html' %}

{% block text %}
  {{ text }}
{% endblock text %}

{% block home %}
  {% lorem 1 b random %}
{% endblock home %}